require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'test/test_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/ApplicationRecord:
  Enabled: false

Metrics/BlockLength:
  Enabled: false